quarkus.log.category."io.quarkiverse.mcp".level=DEBUG
quarkus.log.category."io.vertx".level=DEBUG
quarkus.log.console.color=false

quarkus.console.color=false
quarkus.log.console.color=false


quarkus.http.cors.enabled=true
quarkus.mcp.server.http.streamable.auto-init=true

quarkus.log.category."io.quarkiverse.mcp.server.http.runtime".level=TRACE